language: cpp

sudo: false

before_script:
  - git clone --depth=1 https://github.com/kokkos/kokkos.git && 
    pushd kokkos &&
    mkdir build &&
    pushd build &&
    ../generate_makefile.bash --prefix=$HOME/kokkos --with-openmp --with-serial &&
    make -j2 &&
    make install &&
    popd &&
    popd

addons:
  apt:
    packages:
      - gfortran

script:
  - mkdir build && cd build &&
    cmake -DCMAKE_PREFIX_PATH=$HOME/kokkos -DENABLE_TESTING=ON -DENABLE_EXAMPLES=ON 
          -DCabana_EXTRA_LINK_FLAGS="--coverage" -DCMAKE_CXX_FLAGS="--coverage" .. &&
    make -j2 VERBOSE=1 &&
    make test

after_success:
 - bash <(curl -s https://codecov.io/bash)

cache:
  - ccache

compiler:
  - gcc
