language: cpp

sudo: false

env:
  matrix:
    - BACKENDS="OpenMP"
    - BACKENDS="Serial"
    - BACKENDS="Pthread"
    - BACKENDS="Serial OpenMP"
    - BACKENDS="Serial Pthread"

before_script:
  - git clone --depth=1 https://github.com/kokkos/kokkos.git &&
    pushd kokkos &&
    mkdir build &&
    pushd build &&
    ../generate_makefile.bash --prefix=$HOME/kokkos --with-pthread --with-openmp --with-serial &&
    make -j2 &&
    make install &&
    popd &&
    popd
  - for i in ${BACKENDS}; do CMAKE_OPTS+=( -DCabana_ENABLE_${i}=ON ); done
  - if [[ ${BACKENDS} = *OpenMP* ]]; then export OMP_NUM_THREADS=4; fi


script:
  - mkdir build && pushd build &&
    cmake -DCMAKE_PREFIX_PATH=$HOME/kokkos ${CMAKE_OPTS[@]}
          -DCabana_ENABLE_TESTING=ON -DCabana_ENABLE_EXAMPLES=ON
          -DEXTRA_LINK_FLAGS="--coverage" -DCMAKE_CXX_FLAGS="--coverage" .. &&
    make -j2 VERBOSE=1 &&
    make test &&
    popd

after_success:
 - pushd build && bash <(curl -s https://codecov.io/bash) && popd

cache:
  - ccache

compiler:
  - gcc
